---
title: "Logistic Regression Testing"
author: "A'Bdulla Shanan"
date: "1/13/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Data Preparation 

```{r}
data <- DREAM_DATA_REGRESSION_MODEL
```


```{r}
library(tidyverse)
dataclean <- data %>%
  select(-KEY_A, -SAIL_NIGHTS, -META_PRODUCT_CODE, -BOOKING_STATUS_NAME, 
         -RATE_CAT_CLASS, KEY_AA, -PRODUCT_ID, -ASR_BOOKING_ID, -SAIL_DATE, -UCM_CONSUMER_ID, -PASSENGER_ID, 
          -BOOKING_GENDER, -BRAND, -SHIP_CODE, 
          -CHANNEL, -ADJUSTED_OWNER_DESC, -COMPONENT_CODE,  
         -RDSS_PRODUCT_CODE, -KEY_AA, -ORDER_ID,-PAX_DOCUMENTATION_LANGUAGE,
         -BOUGHT_PRE_CRUISE, -TKT_DIGITAL_CHANNEL, -CHANNEL,-ASR_PRODUCT_BOOKING_DTM,-AMT_GUEST_PAID_BKC, -NET_TICKET_REVENUE_USD, -BOOKING_COMPOSITION,) 
```

## Logistic Regression models


# Product: Deluxe Beverage Package 21+ (17,644)

```{r}
# Set target product equal to 1 
data2 <- dataclean %>%
mutate(COMPONENT_NAME_ADJ = ifelse(grepl('Deluxe Beverage Package 21+', COMPONENT_NAME_ADJ), '1','0'))
# run regression model 
model2 <- glm(as.numeric(COMPONENT_NAME_ADJ)~., family = binomial,data = data2)
summary(model2)
```


# Product: Unlimited  7 Night Dining Package (2,733 observations)

```{r}
# Set target product equal to 1 
data3 <- dataclean %>%
mutate(COMPONENT_NAME_ADJ = ifelse(grepl('Unlimited  7 Night Dining Package', COMPONENT_NAME_ADJ), '1','0'))
# run regression model 
model3 <- glm(as.numeric(COMPONENT_NAME_ADJ)~., family = binomial,data = data3)
summary(model3)
```

# Product: Cooking Class Sushi (2,763)

```{r}
# Set target product equal to 1 
data4 <- dataclean %>%
mutate(COMPONENT_NAME_ADJ = ifelse(grepl('Cooking Class Sushi', COMPONENT_NAME_ADJ), '1','0'))
# run regression model 
model4 <- glm(as.numeric(COMPONENT_NAME_ADJ)~., family = binomial,data = data4)
summary(model4)
```

# Product: Old and New San Juan

```{r}
# Set target product equal to 1 
data5 <- dataclean %>%
mutate(COMPONENT_NAME_ADJ = ifelse(grepl('Old and New San Juan', COMPONENT_NAME_ADJ), '1','0'))
# run regression model 
model5 <- glm(as.numeric(COMPONENT_NAME_ADJ)~., family = binomial,data = data5)
summary(model5)
```


# Product: Couples Swedish Massage 75 mins

```{r}
# Set target product equal to 1 
data1 <- dataclean %>%
mutate(COMPONENT_NAME_ADJ = ifelse(grepl('Couples Swedish Massage 75 mins', COMPONENT_NAME_ADJ), '1','0'))
# run regression model 
model1 <- glm(as.numeric(COMPONENT_NAME_ADJ)~., family = binomial,data = data1)
summary(model1)
```







